Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : regiane
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : christian amarildo 202304940016
// Data atual  : 11/04/2023
Var
raio,diametro:real
Inicio
      escreval("coloque o valor do raio do circulo ")
      leia(raio)
      diametro<-raio*2
      escreval("o diametro do seu circulo é ",diametro)


Fimalgoritmo