Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2023
Var valor, desconto,valorfinal: real

Inicio
escreva("escreva o valor do produto ")
leia (valor)
desconto <-(valor*0.3)
valorfinal<- valor-desconto
escreva ("o valor final é " )
escreva (valorfinal)



Fimalgoritmo

