Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : regiane
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : christian amarildo
// Data atual  : 11/04/2023
Var
nota1,nota2,média:inteiro


Inicio
escreval("escreva a sua nota 1 e a sua nota 2")
leia(nota1,nota2)
média-> (nota1+nota2)/2
escrever("a sua média é " média)
Fimalgoritmo