Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2023
Var numer,numero,numeroo: real

Inicio
escreva("escreva o seu numero ")
leia (numero)
escreva (numero+1)
escreva (numero-1)


Fimalgoritmo

