Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2023
Var raio,volume: real



Inicio
escreva ("coloque o valor de raio ")
leia(raio)
volume <-((4/3)*pi*raio^3)
escreva (volume)


Fimalgoritmo

